### ISSUE TITLE
Crash when using analytic server (Socket.io)

### ISSUE THREAD

**Issue by remotevision** [ccoenraets/nodecellar#11]
When I use just the server.js version the example runs fine. However, when I run the serverwithanalytics.js version it crashes after I make my first request. 

running:
Node v0.9.6
Express v3.3.4

``` javascript
http.js:641
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:641:11)
    at ServerResponse.res.setHeader (/Users/ryan/dev/node/nodecellar/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at SendStream.type (/Users/ryan/dev/node/nodecellar/node_modules/express/node_modules/send/lib/send.js:456:7)
    at SendStream.send (/Users/ryan/dev/node/nodecellar/node_modules/express/node_modules/send/lib/send.js:348:8)
    at /Users/ryan/dev/node/nodecellar/node_modules/express/node_modules/send/lib/send.js:323:10
    at Object.oncomplete (fs.js:93:15)
    at process._makeCallback (node.js:299:20)
```

any thoughts?

**Comment by remotevision** [comment]
nevermind, needed to update my socket.io version
