### ISSUE TITLE
Missing mongodb dependency

### ISSUE THREAD

**Issue by terokaisti** [ccoenraets/nodecellar#2]
87-95-100-192:nodecellar tero$ node server.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/tero/git/test/nodecellar/routes/wines.js:1:75)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by jbueza** [comment]
This ticket is pretty old. I can't reproduce the issue you've described. Below works fine.

```
git clone git://github.com/ccoenraets/nodecellar.git && cd nodecellar
npm install
node server.js
```
